<%-- Example - Rather than including these taglibs on every page,
     I can use a JSP include here for it.  --%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%@ taglib uri="http://www.theospi.org/jsf/osp" prefix="ospx" %>


    <style>
      span.tag {  color: #008000;      }
      span.param  {  color: #A000A0;      }
      span.value  {  color: #000080;      }
    </style>