alter table lesson_builder_groups add siteId varchar(250);

    create table lesson_builder_properties (
        id bigint generated by default as identity (start with 1),
        attribute varchar(255) not null,
        value longvarchar,
        primary key (id),
        unique (attribute)
    );

create index lesson_builder_item_gb on lesson_builder_items(gradebookid);
create index lesson_builder_item_altgb on lesson_builder_items(altGradebook);
create index lesson_builder_prop_idx on lesson_builder_properties(attribute);
create index lesson_builder_group_site on lesson_builder_groups(siteId);
