                 <h:outputText value="This inner text is what goes into the under area." />
                 <h:panelGrid columns="3" styleClass="indnt2">
                    <h:outputText escape="false" value="<strong>Description</strong>
                       This Portfolio contains various assignments from
                       English 311 - Transcendetal American Literature.
                       <br/><strong>Keywords</strong>
                       Writing, Assignments, English 311, Transcendentalism,
                       American Literature"/>
                    <h:outputText escape="false" value="<strong>Layout:</strong> Portfolio Default
                       <br/><strong>Style:</strong> Portfolio Default
                       <br/><strong>Pages:</strong> 4
                       <br/><strong>Size:</strong> 4.5 mb
                       <br/><strong>Modified Date:</strong> August 10, 2005"/>
                    <h:commandButton value="Edit Info" type="button" style="act" />
                 </h:panelGrid>
                 